eureka:
  client:
    service-url:
      defaultZone: http://localhost:13001/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: common
        uri: lb://showcase-common
        order: 1
        predicates:
          - Path=/common/**
        filters:
          - RewritePath=/common/(?<segment>.*), /$\{segment}
custom:
  cors:
    enable: true
