/*
-----------------------------历史数据类表begin-------------------------------
*/

ALTER TABLE ACT_HI_ACTINST 
COMMENT='历史数据-流程实例已完成的所有节点数据';
ALTER TABLE ACT_HI_ACTINST MODIFY COLUMN PROC_INST_ID_ varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '流程实例id';
ALTER TABLE ACT_HI_ACTINST MODIFY COLUMN ACT_ID_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '节点id';
ALTER TABLE ACT_HI_ACTINST MODIFY COLUMN TASK_ID_ varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'user task id';
ALTER TABLE ACT_HI_ACTINST MODIFY COLUMN ACT_NAME_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '节点name';
ALTER TABLE ACT_HI_ACTINST MODIFY COLUMN ACT_TYPE_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '节点类型';
ALTER TABLE ACT_HI_ACTINST MODIFY COLUMN ASSIGNEE_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'task指派人';
ALTER TABLE ACT_HI_ACTINST MODIFY COLUMN START_TIME_ datetime(3) NOT NULL COMMENT '开始时间';
ALTER TABLE ACT_HI_ACTINST MODIFY COLUMN END_TIME_ datetime(3) NULL COMMENT '结束时间';
ALTER TABLE ACT_HI_ACTINST MODIFY COLUMN TENANT_ID_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT '' NULL COMMENT '业务系统标识';


ALTER TABLE ACT_HI_COMMENT 
COMMENT='历史数据-用户审核备注';
ALTER TABLE ACT_HI_COMMENT MODIFY COLUMN TYPE_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '类型，我们关心值为comment的数据';
ALTER TABLE ACT_HI_COMMENT MODIFY COLUMN TIME_ datetime(3) NOT NULL COMMENT '时间';
ALTER TABLE ACT_HI_COMMENT MODIFY COLUMN USER_ID_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '操作人';
ALTER TABLE ACT_HI_COMMENT MODIFY COLUMN TASK_ID_ varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'user task id';
ALTER TABLE ACT_HI_COMMENT MODIFY COLUMN PROC_INST_ID_ varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '流程实例id';
ALTER TABLE ACT_HI_COMMENT MODIFY COLUMN MESSAGE_ varchar(4000) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '简要消息，格式为:通过or拒绝(boolean):审核意见';


ALTER TABLE ACT_HI_DETAIL 
COMMENT='历史数据-流程运行时详情数据';
ALTER TABLE ACT_HI_DETAIL MODIFY COLUMN PROC_INST_ID_ varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '流程实例id';
ALTER TABLE ACT_HI_DETAIL MODIFY COLUMN ACT_INST_ID_ varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'ACT_HI_ACTINST外键';
ALTER TABLE ACT_HI_DETAIL MODIFY COLUMN TASK_ID_ varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'user task id';
ALTER TABLE ACT_HI_DETAIL MODIFY COLUMN NAME_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '变量名称';
ALTER TABLE ACT_HI_DETAIL MODIFY COLUMN VAR_TYPE_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '变量类型';
ALTER TABLE ACT_HI_DETAIL MODIFY COLUMN TIME_ datetime(3) NOT NULL COMMENT '操作时间';
ALTER TABLE ACT_HI_DETAIL MODIFY COLUMN DOUBLE_ double NULL COMMENT 'double类型的值';
ALTER TABLE ACT_HI_DETAIL MODIFY COLUMN LONG_ bigint(20) NULL COMMENT 'long类型的值';
ALTER TABLE ACT_HI_DETAIL MODIFY COLUMN TEXT_ varchar(4000) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'string类型的值1';
ALTER TABLE ACT_HI_DETAIL MODIFY COLUMN TEXT2_ varchar(4000) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'string类型的值2';


ALTER TABLE ACT_HI_IDENTITYLINK 
COMMENT='历史数据-task参与人/组信息';
ALTER TABLE ACT_HI_IDENTITYLINK MODIFY COLUMN GROUP_ID_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'group id';
ALTER TABLE ACT_HI_IDENTITYLINK MODIFY COLUMN TYPE_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '类型：starter/candidate/participant';
ALTER TABLE ACT_HI_IDENTITYLINK MODIFY COLUMN USER_ID_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '直接(指派)参与人';
ALTER TABLE ACT_HI_IDENTITYLINK MODIFY COLUMN TASK_ID_ varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'user task id';
ALTER TABLE ACT_HI_IDENTITYLINK MODIFY COLUMN PROC_INST_ID_ varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '流程实例id';


ALTER TABLE ACT_HI_PROCINST 
COMMENT='历史数据-流程实例主信息';
ALTER TABLE ACT_HI_PROCINST MODIFY COLUMN PROC_INST_ID_ varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '流程实例id';
ALTER TABLE ACT_HI_PROCINST MODIFY COLUMN BUSINESS_KEY_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '业务数据key';
ALTER TABLE ACT_HI_PROCINST MODIFY COLUMN PROC_DEF_ID_ varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '流程定义id，ACT_RE_PROCDEF表外键';
ALTER TABLE ACT_HI_PROCINST MODIFY COLUMN START_TIME_ datetime(3) NOT NULL COMMENT '流程开始时间';
ALTER TABLE ACT_HI_PROCINST MODIFY COLUMN END_TIME_ datetime(3) NULL COMMENT '流程结束时间';
ALTER TABLE ACT_HI_PROCINST MODIFY COLUMN START_USER_ID_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '路程发起人';
ALTER TABLE ACT_HI_PROCINST MODIFY COLUMN START_ACT_ID_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '流程开始的动作id，ACT_HI_ACTINST表外键';
ALTER TABLE ACT_HI_PROCINST MODIFY COLUMN END_ACT_ID_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '流程结束的动作id，ACT_HI_ACTINST表外键';
ALTER TABLE ACT_HI_PROCINST MODIFY COLUMN SUPER_PROCESS_INSTANCE_ID_ varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '父流程id';
ALTER TABLE ACT_HI_PROCINST MODIFY COLUMN TENANT_ID_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT '' NULL COMMENT '业务系统标识';


ALTER TABLE ACT_HI_TASKINST 
COMMENT='历史数据-user task数据';
ALTER TABLE ACT_HI_TASKINST MODIFY COLUMN PROC_DEF_ID_ varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '流程定义id，ACT_RE_PROCDEF表外键';
ALTER TABLE ACT_HI_TASKINST MODIFY COLUMN TASK_DEF_KEY_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'user task的唯一key';
ALTER TABLE ACT_HI_TASKINST MODIFY COLUMN PROC_INST_ID_ varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '流程实例id';
ALTER TABLE ACT_HI_TASKINST MODIFY COLUMN EXECUTION_ID_ varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '流程里的EXECUTION ID，对应ACT_HI_ACTINST表的EXECUTION_ID_';
ALTER TABLE ACT_HI_TASKINST MODIFY COLUMN NAME_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'user task的name';
ALTER TABLE ACT_HI_TASKINST MODIFY COLUMN PARENT_TASK_ID_ varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '父user task id';
ALTER TABLE ACT_HI_TASKINST MODIFY COLUMN ASSIGNEE_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'task指派人';
ALTER TABLE ACT_HI_TASKINST MODIFY COLUMN START_TIME_ datetime(3) NOT NULL COMMENT '开始时间';
ALTER TABLE ACT_HI_TASKINST MODIFY COLUMN CLAIM_TIME_ datetime(3) NULL COMMENT '签收时间';
ALTER TABLE ACT_HI_TASKINST MODIFY COLUMN END_TIME_ datetime(3) NULL COMMENT '结束时间';
ALTER TABLE ACT_HI_TASKINST MODIFY COLUMN TENANT_ID_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT '' NULL COMMENT '业务系统标识';


ALTER TABLE ACT_HI_VARINST 
COMMENT='历史数据-流程变量定义信息';
ALTER TABLE ACT_HI_VARINST MODIFY COLUMN PROC_INST_ID_ varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '流程实例id';
ALTER TABLE ACT_HI_VARINST MODIFY COLUMN EXECUTION_ID_ varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '执行实例ID';
ALTER TABLE ACT_HI_VARINST MODIFY COLUMN TASK_ID_ varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'user task id';
ALTER TABLE ACT_HI_VARINST MODIFY COLUMN NAME_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '参数名称';
ALTER TABLE ACT_HI_VARINST MODIFY COLUMN VAR_TYPE_ varchar(100) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '参数类型';
ALTER TABLE ACT_HI_VARINST MODIFY COLUMN DOUBLE_ double NULL COMMENT 'double值';
ALTER TABLE ACT_HI_VARINST MODIFY COLUMN LONG_ bigint(20) NULL COMMENT 'long值';
ALTER TABLE ACT_HI_VARINST MODIFY COLUMN TEXT_ varchar(4000) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '文本值1';
ALTER TABLE ACT_HI_VARINST MODIFY COLUMN TEXT2_ varchar(4000) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '文本值2';
ALTER TABLE ACT_HI_VARINST MODIFY COLUMN CREATE_TIME_ datetime(3) NULL COMMENT '创建时间';
ALTER TABLE ACT_HI_VARINST MODIFY COLUMN LAST_UPDATED_TIME_ datetime(3) NULL COMMENT '最后更新时间';

/*
-----------------------------历史数据类表end-------------------------------
*/

/*
-----------------------------流程定义类表begin-------------------------------
*/

ALTER TABLE ACT_RE_PROCDEF 
COMMENT='流程定义信息';
ALTER TABLE ACT_RE_PROCDEF MODIFY COLUMN ID_ varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '流程定义id';
ALTER TABLE ACT_RE_PROCDEF MODIFY COLUMN NAME_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '流程定义name';
ALTER TABLE ACT_RE_PROCDEF MODIFY COLUMN KEY_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '流程定义的key';
ALTER TABLE ACT_RE_PROCDEF MODIFY COLUMN VERSION_ int(11) NOT NULL COMMENT '版本';
ALTER TABLE ACT_RE_PROCDEF MODIFY COLUMN DEPLOYMENT_ID_ varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'ACT_RE_DEPLOYMENT表外键';
ALTER TABLE ACT_RE_PROCDEF MODIFY COLUMN RESOURCE_NAME_ varchar(4000) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'bpmn文件信息';
ALTER TABLE ACT_RE_PROCDEF MODIFY COLUMN DGRM_RESOURCE_NAME_ varchar(4000) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'png文件信息';
ALTER TABLE ACT_RE_PROCDEF MODIFY COLUMN TENANT_ID_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT '' NULL COMMENT '业务系统标识';

/*
-----------------------------流程定义类表end-------------------------------
*/

/*
-----------------------------运行时(当前)类表begin-------------------------------
*/

ALTER TABLE ACT_RU_EXECUTION 
COMMENT='当前数据-流程执行实例信息表';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN PROC_INST_ID_ varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '流程实例id';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN BUSINESS_KEY_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '业务数据key';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN PROC_DEF_ID_ varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '流程定义id';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN PARENT_ID_ varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '父id，对应当前表的ID_';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN ACT_ID_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '节点ID';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN IS_CONCURRENT_ tinyint(4) NULL COMMENT '是否并行';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN TENANT_ID_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT '' NULL COMMENT '所属业务系统';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN START_TIME_ datetime(3) NULL COMMENT '开始时间';
ALTER TABLE ACT_RU_EXECUTION MODIFY COLUMN START_USER_ID_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '发起人';


ALTER TABLE ACT_RU_IDENTITYLINK 
COMMENT='当前数据-task参与人/组信息';
ALTER TABLE ACT_RU_IDENTITYLINK MODIFY COLUMN GROUP_ID_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'group';
ALTER TABLE ACT_RU_IDENTITYLINK MODIFY COLUMN TYPE_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '类型：starter/candidate/participant';
ALTER TABLE ACT_RU_IDENTITYLINK MODIFY COLUMN USER_ID_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '直接(指派)参与人';
ALTER TABLE ACT_RU_IDENTITYLINK MODIFY COLUMN TASK_ID_ varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'user task id';
ALTER TABLE ACT_RU_IDENTITYLINK MODIFY COLUMN PROC_INST_ID_ varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '流程实例id';


ALTER TABLE ACT_RU_TASK 
COMMENT='当前数据-user task数据';
ALTER TABLE ACT_RU_TASK MODIFY COLUMN EXECUTION_ID_ varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '流程执行id';
ALTER TABLE ACT_RU_TASK MODIFY COLUMN PROC_INST_ID_ varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '流程实例id';
ALTER TABLE ACT_RU_TASK MODIFY COLUMN PROC_DEF_ID_ varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '流程定义id';
ALTER TABLE ACT_RU_TASK MODIFY COLUMN NAME_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '任务name';
ALTER TABLE ACT_RU_TASK MODIFY COLUMN TASK_DEF_KEY_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '任务key';
ALTER TABLE ACT_RU_TASK MODIFY COLUMN ASSIGNEE_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '签收人（目前签收和审核同步进行）';
ALTER TABLE ACT_RU_TASK MODIFY COLUMN CREATE_TIME_ timestamp(3) NULL COMMENT '任务创建时间';
ALTER TABLE ACT_RU_TASK MODIFY COLUMN TENANT_ID_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT '' NULL COMMENT '业务系统标识';


ALTER TABLE ACT_RU_VARIABLE 
COMMENT='当前数据-运行变量信息';
ALTER TABLE ACT_RU_VARIABLE MODIFY COLUMN TYPE_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '数据类型';
ALTER TABLE ACT_RU_VARIABLE MODIFY COLUMN NAME_ varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '变量名称';
ALTER TABLE ACT_RU_VARIABLE MODIFY COLUMN EXECUTION_ID_ varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '流程执行id';
ALTER TABLE ACT_RU_VARIABLE MODIFY COLUMN PROC_INST_ID_ varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '流程实例id';
ALTER TABLE ACT_RU_VARIABLE MODIFY COLUMN TASK_ID_ varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '任务id';
ALTER TABLE ACT_RU_VARIABLE MODIFY COLUMN DOUBLE_ double NULL COMMENT 'double值';
ALTER TABLE ACT_RU_VARIABLE MODIFY COLUMN LONG_ bigint(20) NULL COMMENT 'long值';
ALTER TABLE ACT_RU_VARIABLE MODIFY COLUMN TEXT_ varchar(4000) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '文本值1';
ALTER TABLE ACT_RU_VARIABLE MODIFY COLUMN TEXT2_ varchar(4000) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '文本值2';

/*
-----------------------------运行时(当前)类表end-------------------------------
*/